In [1]:
import pandas as pd
pd.set_option('display.max_Colwidth',None)

In [2]:
df = pd.read_csv("hindi_dataset.tsv" ,sep="\t",
    engine="python",
    quoting=3,
    on_bad_lines="skip")

In [3]:
df.head()

,text_id,text,task_1,task_2,task_3
0,hasoc_hi_5556,"बांग्लादेश की शानदार वापसी, भारत को 314 रन पर रोका #INDvBAN #CWC19",NOT,NONE,NONE
1,hasoc_hi_5648,सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांतीदूत के साथ कुछ होगा सब #रंडीरोना शुरू कर देंगे,HOF,PRFN,UNT
2,hasoc_hi_164,तुम जैसे हरामियों के लिए बस जूतों की कमी है शुक्र कर अभी तुम्हारी लिंचिंग हुई नहीं है हिंदुओं के जागने की देर है सच में होगी अभी तो तुम जैसे हरामी सुवर ड्रामा बनाएं हो सुवर कहीं का मौलाना। तुम जैसे हरामियों कुत्ते की मौत मारना चाहिए सुवर जैसी शक्ल रंडी की औलाद सुवर कहीं का ।।।।,HOF,PRFN,TIN
3,hasoc_hi_3530,"बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत मिलने की खुशी में एक समर्थक ने इंदौर में हर्ष फायरिंग की #AkashVijayvargiya https://abpnews.abplive.in/india-news/celebratory-firing-outside-bjp-mla-akash-vijayvargiya-office-in-indore-1157241 …",NOT,NONE,NONE
4,hasoc_hi_5206,"चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर्शन, तेजस्वी यादव नदारद #biharencephalitisdeaths https://abpnews.abplive.in/bihar-news/aes-deaths-rjd-protest-in-vidhan-sabha-campus-but-tejashwi-yadav-was-not-present-1158748 … (रिपोर्ट- @kumarprakash4u )",NOT,NONE,NONE

In [4]:
df['Label_binary'] = df['task_1'].map({'HOF':1,'NOT':0})

In [5]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4665 entries, 0 to 4664
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   text_id       4665 non-null   object
 1   text          4665 non-null   object
 2   task_1        4665 non-null   object
 3   task_2        4665 non-null   object
 4   task_3        4665 non-null   object
 5   Label_binary  4665 non-null   int64
dtypes: int64(1), object(5)
memory usage: 218.8+ KB

In [6]:
df = df[['text' , 'Label_binary']]

In [7]:
df.head()
# the dataset is ready for the translation purpose and ease for better understanding

,text,Label_binary
0,"बांग्लादेश की शानदार वापसी, भारत को 314 रन पर रोका #INDvBAN #CWC19",0
1,सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांतीदूत के साथ कुछ होगा सब #रंडीरोना शुरू कर देंगे,1
2,तुम जैसे हरामियों के लिए बस जूतों की कमी है शुक्र कर अभी तुम्हारी लिंचिंग हुई नहीं है हिंदुओं के जागने की देर है सच में होगी अभी तो तुम जैसे हरामी सुवर ड्रामा बनाएं हो सुवर कहीं का मौलाना। तुम जैसे हरामियों कुत्ते की मौत मारना चाहिए सुवर जैसी शक्ल रंडी की औलाद सुवर कहीं का ।।।।,1
3,"बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत मिलने की खुशी में एक समर्थक ने इंदौर में हर्ष फायरिंग की #AkashVijayvargiya https://abpnews.abplive.in/india-news/celebratory-firing-outside-bjp-mla-akash-vijayvargiya-office-in-indore-1157241 …",0
4,"चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर्शन, तेजस्वी यादव नदारद #biharencephalitisdeaths https://abpnews.abplive.in/bihar-news/aes-deaths-rjd-protest-in-vidhan-sabha-campus-but-tejashwi-yadav-was-not-present-1158748 … (रिपोर्ट- @kumarprakash4u )",0

###### df['Label_binary'].value_counts()

In [17]:
!pip install deep_translator

Collecting deep_translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\users\lenovo\anaconda3\lib\site-packages (from deep_translator) (4.12.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\lenovo\anaconda3\lib\site-packages (from deep_translator) (2.32.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\lenovo\anaconda3\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2025.10.5)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
Installing collected packages: deep_translator
Successfully installed deep_translator-1.11.4

In [27]:
from deep_translator import GoogleTranslator
import time

In [35]:

# print(f"Starting translation for {len(df)} rows...")

# translator = GoogleTranslator(source='auto', target='en')
# translated_texts = []  # Changed to plural

# for index, text in enumerate(df['text']):
#     text_str = str(text)
    
#     try:
#         # Fixed typo: changed tramlator to translator
#         english_text = translator.translate(text_str)
#         translated_texts.append(english_text)  # Changed to plural
#     except Exception as e:
#         print(f"Error at row {index}: {e}")
#         translated_texts.append("")  # Changed to plural
        
#     if index % 100 == 0 and index > 0:
#         print(f"Translated {index} rows out of {len(df)}...")
        
#     # Sleep for half a second to avoid Error 429 (Too Many Requests)
#     time.sleep(0.5)

# # 4. Add the translated text as a new column
# df['translated_text'] = translated_texts  # Changed to plural

# # 5. SAVE IT! So you never have to wait 40 minutes again!
# df.to_csv("translated_hindi_dataset.csv", index=False)
print("Done! Saved as 'translated_hindi_dataset.csv'.")

Starting translation for 4665 rows...
Translated 100 rows out of 4665...
Error at row 109: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Translated 200 rows out of 4665...
Translated 300 rows out of 4665...
Translated 400 rows out of 4665...
Translated 500 rows out of 4665...
Translated 600 rows out of 4665...
Translated 700 rows out of 4665...
Translated 800 rows out of 4665...
Error at row 856: ("Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Translated 900 rows out of 4665...
Translated 1000 rows out of 4665...
Translated 1100 rows out of 4665...
Error at row 1155: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Translated 1200 rows out of 4665...
Translated 1300 rows out of 4665...
Error at row 1321: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=en&sl=auto&q=Jharkhand+ke+%23Tabrez_Ansari+ko+%40aimim_national+jharkhand+ki+team++madad+karegi%2C++Qatilo+ke+khilaf+pura+muqadma+aimim+president+jb+%23Hubban_Malik+sahab+aur+unki+team+ladegi++%40asadowaisi (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024FAA62DF90>: Failed to resolve 'translate.google.com' ([Errno 11001] getaddrinfo failed)"))
Translated 1400 rows out of 4665...
Translated 1500 rows out of 4665...
Translated 1600 rows out of 4665...
Translated 1700 rows out of 4665...
Translated 1800 rows out of 4665...
Translated 1900 rows out of 4665...
Error at row 1975: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Translated 2000 rows out of 4665...
Translated 2100 rows out of 4665...
Translated 2200 rows out of 4665...
Translated 2300 rows out of 4665...
Translated 2400 rows out of 4665...
Translated 2500 rows out of 4665...
Translated 2600 rows out of 4665...
Translated 2700 rows out of 4665...
Translated 2800 rows out of 4665...
Translated 2900 rows out of 4665...
Translated 3000 rows out of 4665...
Translated 3100 rows out of 4665...
Translated 3200 rows out of 4665...
Translated 3300 rows out of 4665...
Error at row 3301: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=en&sl=auto&q=%E2%80%98%E0%A4%AC%E0%A5%88%E0%A4%9F%E0%A4%AE%E0%A5%87%E0%A4%A8%E2%80%99+%E0%A4%B5%E0%A4%BF%E0%A4%A7%E0%A4%BE%E0%A4%AF%E0%A4%95+%E0%A4%B8%E0%A5%87+%E0%A4%AA%E0%A5%80%E0%A4%8F%E0%A4%AE+%40narendramodi+%E0%A4%A8%E0%A4%BE%E0%A4%B0%E0%A4%BE%E0%A4%9C%E0%A4%BC%2C+%E0%A4%A6%E0%A5%8B+%E0%A4%9F%E0%A5%82%E0%A4%95+%E0%A4%95%E0%A4%B9%E0%A4%BE-+%E0%A4%AC%E0%A5%87%E0%A4%9F%E0%A4%BE+%E0%A4%B8%E0%A4%BE%E0%A4%82%E0%A4%B8%E0%A4%A6+%E0%A4%95%E0%A4%BE+%E0%A4%B9%E0%A5%8B+%E0%A4%AF%E0%A4%BE+%E0%A4%AE%E0%A4%82%E0%A4%A4%E0%A5%8D%E0%A4%B0%E0%A5%80+%E0%A4%95%E0%A4%BE%2C+%E0%A4%90%E0%A4%B8%E0%A5%80+%E0%A4%B9%E0%A4%B0%E0%A4%95%E0%A4%A4+%E0%A4%AC%E0%A4%B0%E0%A5%8D%E0%A4%A6%E0%A4%BE%E0%A4%B6%E0%A5%8D%E0%A4%A4+%E0%A4%A8%E0%A4%B9%E0%A5%80%E0%A4%82++++%23akashvijayvargiya+%23KailashVijayvargiya (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024FB1B12710>: Failed to resolve 'translate.google.com' ([Errno 11001] getaddrinfo failed)"))
Translated 3400 rows out of 4665...
Translated 3500 rows out of 4665...
Translated 3600 rows out of 4665...
Error at row 3607: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=en&sl=auto&q=%E0%A4%86%E0%A4%AA+%E0%A4%B8%E0%A4%AC+%E0%A4%A6%E0%A5%87%E0%A4%B6%E0%A4%B5%E0%A4%BE%E0%A4%B8%E0%A4%BF%E0%A4%AF%E0%A5%8B%E0%A4%82+%E0%A4%95%E0%A5%8B+%E0%A4%88%E0%A4%A6+%E0%A4%AE%E0%A5%81%E0%A4%AC%E0%A4%BE%E0%A4%B0%E0%A4%95+%E0%A4%86%E0%A4%AA%E0%A4%95%E0%A4%BE+%E0%A4%85%E0%A4%AA%E0%A4%A8%E0%A4%BE+%23%E0%A4%AE%E0%A5%8B%E0%A4%A1%E0%A5%80%E0%A4%BC++%E0%A4%AF%E0%A4%BE+%23%E0%A4%85%E0%A4%B2%E0%A5%8D%E0%A4%B2%E0%A4%BE%E0%A4%B9+%E0%A4%AE%E0%A5%87%E0%A4%B0%E0%A5%87+%23%E0%A4%AE%E0%A4%A8%E0%A4%B9%E0%A5%82%E0%A4%B8%2C+%23%E0%A4%85%E0%A4%82%E0%A4%A7%E0%A4%AD%E0%A4%95%E0%A5%8D%E0%A4%A4%E0%A5%8B%E0%A4%82+%E0%A4%94%E0%A4%B0+%23%E0%A4%AE%E0%A4%BE%E0%A4%A8%E0%A4%B8%E0%A4%BF%E0%A4%95_%E0%A4%97%E0%A5%81%E0%A4%B2%E0%A4%BE%E0%A4%AE%E0%A5%8B+%E0%A4%95%E0%A5%8B+%23%E0%A4%95%E0%A5%81%E0%A4%A4%E0%A5%8D%E0%A4%A4%E0%A5%87+%E0%A4%95%E0%A5%80+%E0%A4%AE%E0%A5%8C%E0%A4%A4+%E0%A4%A6%E0%A5%87+...++++%23%E0%A4%86%E0%A4%AE%E0%A5%80%E0%A4%A8 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1028)')))
Translated 3700 rows out of 4665...
Translated 3800 rows out of 4665...
Translated 3900 rows out of 4665...
Translated 4000 rows out of 4665...
Error at row 4001: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Translated 4100 rows out of 4665...
Translated 4200 rows out of 4665...
Error at row 4277: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Translated 4300 rows out of 4665...
Translated 4400 rows out of 4665...
Translated 4500 rows out of 4665...
Error at row 4547: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Translated 4600 rows out of 4665...
Done! Saved as 'translated_hindi_dataset.csv'.

In [41]:
df_translated = pd.read_csv('translated_hindi_dataset.csv')

In [44]:
df_translated.sample(10)

,text,Label_binary,translated_text
4657,"BJP भी जानती है कि यह हरामी बदशकल बहुत ही महाचूतिया, सुअर से भी गिरा इंसान है, बुरा ना मानो कीचड़ से लथपथ इस जानवर का @ManojTiwariMP @DocVatsa @AamAadmiParty @ravi4354 @JanLokPaal",1,"BJP also knows that this scoundrel is a big ass, a person lower than a pig, don't feel bad about this animal covered in mud @ManojTiwariMP @DocVatsa @AamAadmiParty @ravi4354 @JanLokPaal"
1055,इस हरामी को चौराहे पर उल्टा लटका कर मारो। कानून तो सत्ता के हाथ की रखैल बन चूका तभी मुजरिमों की हिम्मत बढ़ गई है। वरना एसे पागल कुत्तों को चैराहे पर गोली मार देनी चाहये।,1,Beat this bastard by hanging him upside down at the crossroads. The law has become the mistress of the government and that is why the courage of the criminals has increased. Otherwise such mad dogs should be shot at the crossroads.
4465,"शहीदों के नाम पर “सियासत” करते करते तुम “संसद” में 303 हो गये, लेकिन अब इतना तो बता दो, कि सेना के बहादुर जवानों के “रोज़” शहीद होने का सिलसिला कब तक रुकेगा.",1,"While doing “politics” in the name of martyrs, you became 303 in the “Parliament”, but now tell me, when will the trend of brave army soldiers getting martyred “daily” stop?"
1788,खूब लड़ी मर्दानी वह तो झाँसी वाली रानी थी।। #म #मराठी #झाशीचीराणी #लक्ष्मीबाई या क्रांतिकारकांच्या व स्फूर्तीदेवता होत्या.... स्मृतिदिनी विनम्र अभिवादन,0,Khub Ladi Mardani Vah To Jhansi Wali Rani Thi. #M #Marathi #JhashiChirani #Laxmibai was the goddess of inspiration of these revolutionaries.... Humble greetings on Memorial Day
2543,bhut sahi ye Mahamahim ji bhi chuppi sadhe h sirf SP ki sarkaar me khulta tha..dhanya ho Mahamahim ji aapne to pad ki bhi garima gira di..,0,It is true that Mahamahim ji has also remained silent and it was revealed only in SP government.. I am saying that Mahamahim ji has also brought down the dignity of his father.
3181,तेरी बहनी महतरी लौंडिया की chut पशिया की झाँट माँदर chod मुँह में लुँड कर दूँगा,1,"Mother Chod, I will put my penis in your mouth, the pussy of your sister Mahtari Laundiya."
3062,"#ZairaWaseem ने जिस ईमान की दुहाई देकर फिल्मों को खुदा हाफिज कहा है, क्या नुसरत जहां, जोया अख्तर और कौसर मुनीर का ईमान उनसे कम है?",1,"Is the faith of Nusrat Jahan, Zoya Akhtar and Kausar Munir less than that of the faith that #ZairaWaseem has invoked and called films God Hafiz?"
4062,चिराग तले अंधेरा इसी को कहते हैं। अपनी बेटी के अच्छे काम और पार्टी के सहयोग की प्रशंसा करने कि जगह मोदी जैसे #नीच के फैन हैं। मां बाप का सम्मान जरूर करना चाहिए लेकिन अपनी सोच और उसुलों से समझौता नहीं करना चाहिए। मुझे आज तक समझ नहीं आया लोग मोदी जैसे दंगाई के फैन कैसे हो सकते हैं?,1,"This is called darkness under the lamp. Instead of praising his daughter's good work and party's support, he is a fan of #Neech like Modi. One must respect parents but one must not compromise with one's thoughts and principles. Till date I have not understood how people can be fans of a rioter like Modi?"
4433,बस एक कहानी कहानी उस औरत की जो थी बहुत ही हरामी...,1,Just a story about a woman who was a very bastard...
2787,सर अगर आप उन सुअर की औलादों के खिलाफ कुछ बोल नही सकते हो तो इससे अच्छा होगा कि आप इस मुद्दे पे कुछ भी न बोलो,1,"Sir, if you cannot say anything against those pigs, then it would be better if you do not say anything on this issue."

In [43]:
df_translated.isnull().sum()

text                0
Label_binary        0
translated_text    10
dtype: int64

In [53]:
df_translated.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4655 entries, 0 to 4664
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   text             4655 non-null   object
 1   Label_binary     4655 non-null   int64
 2   translated_text  4655 non-null   object
dtypes: int64(1), object(2)
memory usage: 145.5+ KB

In [47]:
df_translated.duplicated().sum()

np.int64(0)

In [51]:
df_translated = df_translated.dropna()

In [54]:
df_translated.isnull().sum()

text               0
Label_binary       0
translated_text    0
dtype: int64

# Clean up begun..

In [56]:
"Unnamed : 0" in df.columns

False

In [59]:
print("See the distribution of 0's and 1's:\n",df_translated['Label_binary'].value_counts())

See the distribution of 0's and 1's:
 Label_binary
1    2465
0    2190
Name: count, dtype: int64